server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://44.223.54.192:8761/eureka/

spring:
  application:
    name: mcsv-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: hotel-dev
          uri: http://44.223.54.192:8081
          predicates:
            - Path=/hotel/**
        - id: habitaciones-dev
          uri: http://44.223.54.192:8081
          predicates:
            - Path=/habitaciones/**
        - id: calificaciones-hotel-dev
          uri: http://44.223.54.192:8081
          predicates:
            - Path=/calificacion/**
        - id: reservacion-dev
          uri: http://44.223.54.192:8081
          predicates:
            - Path=/reservacion/**
        - id: usuario-dev
          uri: http://44.223.54.192:8082
          predicates:
            - Path=/usuario/**
        - id: restaurante-dev
          uri: http://44.223.54.192:8085
          predicates:
            - Path=/restaurante/**
        - id: platillos-dev
          uri: http://44.223.54.192:8085
          predicates:
            - Path=/platillos/**
        - id: calificacion-platillos-dev
          uri: http://44.223.54.192:8085
          predicates:
            - Path=/calificacionRestaurante/**
        - id: persona-dev
          uri: http://44.223.54.192:8082
          predicates:
            - Path=/persona/**
        - id: empleado-hotel-dev
          uri: http://44.223.54.192:8082
          predicates:
            - Path=/empleadoHotel/**
        - id: empleado-restaurante-dev
          uri: http://44.223.54.192:8082
          predicates:
            - Path=/empleadoRestaurante/**
        - id: factura-hotel-dev
          uri: http://44.223.54.192:8083
          predicates:
            - Path=/detalleFactura/**
        - id: detalle-factura-restaurante-dev
          uri: http://44.223.54.192:8083
          predicates:
            - Path=/detalleFacturaRestaurante/**
        - id: factura-restaurante-dev
          uri: http://44.223.54.192:8083
          predicates:
            - Path=/facturaRestaurante/**

