server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://44.223.54.192:8761/eureka/

spring:
  application:
    name: mcsv-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: hotel-dev
          uri: http://44.223.54.192:8081
          predicates:
            - Path=/hotel/**
        - id: habitaciones-dev
          uri: http://44.223.54.192:8081
          predicates:
            - Path=/habitaciones/**
        - id: calificaciones-hotel-dev
          uri: http://44.223.54.192:8081
          predicates:
            - Path=/calificacion/**
        - id: clientes-dev-clientes
          uri: http://44.223.54.192:8184
          predicates:
            - Path=/clientes/**

