server:
  port: 8083

spring:
  application:
    name: mcsv-facturacion

  datasource:
    #  driver-class-name: com.mysql.cj.jdbc.Driver

    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/facturacion_mcsv
    username: root
    password: password


  jpa:
    hibernate:
      ddl-auto: update
    # database: mariabd
    database-platform: org.hibernate.dialect.MariaDBDialect

#database-platform: org.hibernate.dialect.MySQL8Dialect

