server:
    port: 8082

spring:
    application:
        name: mcsv-usuario

    datasource:
        #  driver-class-name: com.mysql.cj.jdbc.Driver

        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://mcsv-usuario.cctockmoifnj.us-east-1.rds.amazonaws.com:3306/mcsv_usuario
        username: admin
        password: GS2Jk48xQkAe2cuFw8aU


    jpa:
        hibernate:
            ddl-auto: update
        # database: mariabd
        database-platform: org.hibernate.dialect.MariaDBDialect

#database-platform: org.hibernate.dialect.MySQL8Dialect
    security:
        jwt:
            secret-key: k7ehq9LLttTbATjmp82uAm1DjrGoUn5fGhWW8n9t64I=
            secret-expiration-time: 3600000

eureka:
    client:
        service-url:
            defaultZone: http://44.223.54.192:8761/eureka/
        register-with-eureka: true
        fetch-registry: true