server:
  port: 8761
  address: 0.0.0.0   

spring:
  application:
    name: mcsv-eureka

eureka:
  instance:
    hostname: 44.223.54.192
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://44.223.54.192:8761/eureka/
