server:
  port: 8085

spring:
  application:
    name: mcsv-restaurante

  datasource:
    #  driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://restaurante-mcsv.cctockmoifnj.us-east-1.rds.amazonaws.com:3306/restaurante_mcsv
    username: admin
    password: password

# pDwCNHMaCJx8kS5ed8Qu

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://44.223.54.192:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#database-platform: org.hibernate.dialect.MySQL8Dialect

