server:
  port: 8081

spring:
  application:
    name: mcsv-hoteleria

  datasource:
  #  driver-class-name: com.mysql.cj.jdbc.Driver

    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:hoteleria-mcsv.cctockmoifnj.us-east-1.rds.amazonaws.com/hoteleria-mcsv
   # url: jdbc:mariadb://localhost:3306/hoteleria_mcsv
    username: admin
    password: password


  jpa:
    hibernate:
      ddl-auto: update
   # database: mariabd
    database-platform: org.hibernate.dialect.MariaDBDialect

#database-platform: org.hibernate.dialect.MySQL8Dialect

