server:
  port: 8081

spring:
  application:
    name: mcsv-hoteleria


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://hoteleria.cctockmoifnj.us-east-1.rds.amazonaws.com:3306/hoteleria_mcsv
    username: admin
    password: AgAzjSglkmJY6823uFCQ
  #datasource:
  #  driver-class-name: com.mysql.cj.jdbc.Driver

    #driver-class-name: org.mariadb.jdbc.Driver
   # url: jdbc:mariadb://clase2-semi1.cctockmoifnj.us-east-1.rds.amazonaws.com:3306
   # url: jdbc:mariadb://localhost:3306/hoteleria_mcsv
 #   username: admin
   # password: password


  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect

eureka:
  client:
    service-url:
      defaultZone: http://44.223.54.192:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

   # hibernate:
   #   ddl-auto: update
   # database: mariabd
   # database-platform: org.hibernate.dialect.MariaDBDialect

#database-platform: org.hibernate.dialect.MySQL8Dialect

